### PR TITLE
Update mute

### PR DESCRIPTION
**Pull request by ghost**
Update mute
Few fixes

### CODE REVIEW

**Comment by ghost** [comment]
We can have live review sessions if you want to. The change is not so small after all :)

**Comment by cdimascio** [comment]
@Mykolas-Molis that sounds good. i have a busy week ahead, would perhaps friday work?

**Comment by ghost** [comment]
Sure - ping me on Friday when ready

**Comment by ghost** [comment]
So - going to take a look today?

**Comment by cdimascio** [comment]
yes. are you free at 2pm EST? how can i reach you?

**Comment by ghost** [comment]
2pm sounds good, lets meet on hangouts?

Sent from my iPhone

On 23 Feb 2018, at 15:50, Carmine DiMascio <notifications@github.com<mailto:notifications@github.com>> wrote:


yes. are you free at 2pm EST? how can i reach you?

-

**Comment by cdimascio** [comment]
do u have a hangouts link to join - im cdimascio on hangouts. im also free after 4pm EST

**Comment by cdimascio** [comment]
@Mykolas-PO shall we try to connect again? u can reach me on hangouts at cdimascio@g mail.com

**Review by cdimascio — DISMISSED** [review]

**Comment by cdimascio** [comment]
@Mykolas-Molis @Mykolas-PO please update the version in package.json to 2.0.0, then i'll merge it in

**Comment by cdimascio** [comment]
Thanks so much for your work here 👍

**Comment by ghost** [comment]
Sorry for keep closing and reopening - I changed version to 2.0.0. I think you can merge it now and perform release.

**Comment by ghost** [comment]
I updated README doc

**Comment by ghost** [comment]
Any plans to release this any time soon?

**Comment by cdimascio** [comment]
@Mykolas-Molis yes. we can bring this in. there are still conflicts on the branch. Once you have them resolved,  I will merge it in. The changes look good. Thanks again for you fantastic work!

**Comment by ghost** [comment]
I resolved the conflicts. PR is ready to be merged.

**Pull request merged**
