### PR TITLE
Fix mute

### PR DESCRIPTION
**Pull request by ghost**
Mute currently mutes more messages than it should.

### CODE REVIEW

**Comment by cdimascio** [comment]
@Mykolas-Molis , thanks a lot for the fix. Looks great. Merging.

**Comment by cdimascio** [comment]
I'll roll a new version with your fix tonight and publish to npm

**Comment by ghost** [comment]
Wow - that was fast - thanks! :)

**Comment by cdimascio** [comment]
@Mykolas-Molis if you're interested, i'm thinking to add a contributors section on the README page for the project. would you like to be added?

**Comment by ghost** [comment]
Yes I would. I would prepare PR too.

**Comment by cdimascio** [comment]
@Mykolas-Molis sure thing. in the meantime i've added you to the readme. thanks again!

**Pull request merged**
